name: Sync from Reddit

on:
  workflow_dispatch:
  schedule:
    # run hourly at some arbitrary minute
    - cron: 3 * * * *

jobs:
  sync-from-reddit:
    name: Sync from Reddit
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Download wiki from Reddit
        run: ./download-wiki.sh

      - name: Push changes (if any)
        run: git push

  # Pushes from GitHub Actions do not trigger further actions; manually call deploy
  deploy:
    name: Deploy site
    needs: sync-from-reddit
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy.yml
